import { Inter } from 'next/font/google'
import './globals.css'
import TopHeader from '../components/TopHeader'
import SearchHeader from '../components/SearchHeader'
import ClientProviderTheme from "./ClientProviderTheme";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClientProviderTheme>
        <body className={inter.className}>
          <TopHeader/>
          <SearchHeader/>
          {children}
        </body>
      </ClientProviderTheme>
    </html>
  )
}
