import { Inter } from 'next/font/google'
import './globals.css'
import TopHeader from '../components/Header-Footer/Top-Header/TopHeader'
import SearchHeader from '../components/Header-Footer/Search-Header/SearchHeader'
import ClientProviderTheme from "./ClientProviderTheme";
import Footer from '../components/Header-Footer/Footer/Footer';
import Sticktbar from '../components/Home-Page/Stickybar/Sticktbar';
import ClientProviderRedux from './ClientProviderRedux'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClientProviderTheme>
        <body className={inter.className}>
          <ClientProviderRedux>
            <TopHeader/>
            <SearchHeader/>
            {children}
            <Footer/>
            <Sticktbar/>
          </ClientProviderRedux>
        </body>
      </ClientProviderTheme>
    </html>
  )
}
